name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  WORKDIR: ~/mod-workdir

jobs:
  toolchain:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: toolchain-workdir
          path: ~/mod-workdir
      - name: make toolchain
        run: make toolchain
