name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  WORKDIR: /home/runner/mod-workdir

jobs:
  toolchain:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: toolchain-workdir
          path: /home/runner/mod-workdir
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: make toolchain
        run: |
          mkdir -p /home/runner/mod-workdir
          chmod 777 /home/runner/mod-workdir
          make toolchain
