name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  WORKDIR: /home/runner/mod-workdir

jobs:
  toolchain:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: toolchain
          path: /home/runner/mod-workdir
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: make toolchain
        run: |
          make toolchain
      - name: pack toolchain
        run: |
          tar -C /home/runner/mod-workdir -czf workdir-toolchain.tar.gz x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: workdir-toolchain
          path: workdir-toolchain.tar.gz

  bootstrap:
    needs: toolchain
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: bootstrap
          path: /home/runner/mod-workdir
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - uses: actions/download-artifact@v2
        with:
          name: workdir-toolchain
          path: /home/runner
      - name: Extract workdir-toolchain
        shell: bash
        run: |
            mkdir -p /home/runner/mod-workdir
            cd /home/runner/mod-workdir && sudo tar -x --overwrite -f ../workdir-toolchain.tar.gz
      - name: make bootstrap
        run: |
          make bootstrap
      - name: pack bootstrap
        run: |
          tar -C /home/runner/mod-workdir -czf workdir-bootstrap.tar.gz x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: workdir-bootstrap
          path: workdir-bootstrap.tar.gz

  mod-os:
    needs: bootstrap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: mod-os
          path: /home/runner/mod-workdir
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - uses: actions/download-artifact@v2
        with:
          name: workdir-bootstrap
          path: /home/runner
      - name: Extract workdir-bootstrap
        shell: bash
        run: |
            mkdir -p /home/runner/mod-workdir
            cd /home/runner/mod-workdir && sudo tar -x --overwrite -f ../workdir-bootstrap.tar.gz
      - name: make mod-os
        run: |
          make mod-os
      - name: pack mod-os
        run: |
          tar -C /home/runner/mod-workdir -czf workdir-mod-os.tar.gz x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: workdir-mod-os
          path: workdir-mod-os.tar.gz

  #plugins-bootstrap:
    #needs: toolchain
    #runs-on: ubuntu-20.04
    #steps:
      #- uses: actions/checkout@v2
      #- uses: satackey/action-docker-layer-caching@v0.0.11
      #- name: make plugins-bootstrap
        #run: |
          #make plugins-bootstrap
