name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  toolchain:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: make toolchain
        run: make toolchain
